name: Build site

on:
  # Called from website publish and PR checks
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Download C apidocs artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: onnxruntime-c-apidocs
          workflow: publish-c-apidocs.yml
          branch: main
          path: apidocs

      - name: Download C# apidocs artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: onnxruntime-csharp-apidocs
          workflow: publish-csharp-apidocs.yml
          branch: main
          path: apidocs

      - name: Download Java apidocs artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: onnxruntime-java-apidocs
          workflow: publish-java-apidocs.yml
          branch: main
          path: apidocs

      - name: Download Python apidocs artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: onnxruntime-python-apidocs
          workflow: publish-python-apidocs.yml
          branch: main
          path: apidocs

      - name: Move apidocs folder into place
        run: |
          sudo rm -rf _site/docs/api/c
          sudo mv apidocs/docs/api/c _site/docs/api
          sudo rm -rf _site/docs/api/csharp
          sudo mv apidocs/docs/api/csharp _site/docs/api
          sudo rm -rf _site/docs/api/java
          sudo mv apidocs/docs/api/java _site/docs/api
          sudo rm -rf _site/docs/api/python
          sudo mv apidocs/docs/api/python _site/docs/api

      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Check for broken links
        run: |
          bundle exec htmlproofer --assume_extension --checks_to_ignore ImageCheck,ScriptCheck --only_4xx --http_status_ignore 429,403 --allow_hash_href --url_ignore "https://onnxruntime.ai/docs/reference/api/c-api.html,https://www.onnxruntime.ai/docs/reference/execution-providers/TensorRT-ExecutionProvider.html#c-api-example,https://www.onnxruntime.ai/docs/resources/graph-optimizations.html,onnxruntime/capi/onnxruntime_pybind11_state.html" --log-level :info ./_site

      - name: Upload site contents
        uses: actions/upload-artifact@v3
        with:
          path: _site
          name: onnxruntime-content
