name: Update C/C++ API Docs
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    name: Generate C/C++ API docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install doxygen and dependencies
        run: |
          sudo apt update
          sudo apt-get install libclang-9-dev
          sudo apt-get install libclang-cpp9
          wget https://www.doxygen.nl/files/doxygen-1.9.2.linux.bin.tar.gz
          tar xvzf doxygen-1.9.2.linux.bin.tar.gz
      - name: Run doxygen
        run: |
          mkdir -p build/doxygen
          cd docs/c_cxx
          ../../doxygen-1.9.2/bin/doxygen
      - uses: actions/upload-artifact@v3
        with:
          name: c-apidocs
          path: build/doxygen/html
          retention-days: 90

  build-and-deploy-website:
    needs: "generate"
    uses: ./.github/workflows/pages.yml
